//
// Created by painnick on 2024-11-15.
//

#ifndef GUNDAMQUALITY2_ESP32C3_SRC_COMMON_H_
#define GUNDAMQUALITY2_ESP32C3_SRC_COMMON_H_

#include "esp_log.h"

#define PIN_STEP_MOTOR_STEP 3
#define PIN_STEP_MOTOR_ENABLE 4
#define PIN_HALL_SENSOR 5
#define PIN_NECK_SERVO 6
#define PIN_GUNDAM_EYE 7

#define CH_GUNDAM_EYE 5

#define STEPS_PER_REV 2048

#define NECK_ANGLE_START 90
#define NECK_ANGLE_LEFT 150


#define GUNDAM_EYE_TURN_ON() (ledcWrite(CH_GUNDAM_EYE, 95))
#define GUNDAM_EYE_EMPHASIZE() (ledcWrite(CH_GUNDAM_EYE, 191))
#define GUNDAM_EYE_TURN_OFF() (ledcWrite(CH_GUNDAM_EYE, 0))

#endif //GUNDAMQUALITY2_ESP32C3_SRC_COMMON_H_
